### ISSUE TITLE
Windows Compatibility

### ISSUE THREAD

**Issue by davepsilon** [brandon-rhodes/python-jplephem#13]
daf.py fails in the mmap creation on Windows.  I believe a simple change will fix it, changing the offset from PAGESIZE to ALLOCATIONGRANULARITY  

https://docs.python.org/2/library/mmap.html
Windows Constructor: "offset may be specified as a non-negative integer offset. mmap references will be relative to the offset from the beginning of the file. offset defaults to 0. offset must be a multiple of the ALLOCATIONGRANULARITY."

Unix Constructor:  "offset may be specified as a non-negative integer offset. mmap references will be relative to the offset from the beginning of the file. offset defaults to 0. offset must be a multiple of the PAGESIZE or ALLOCATIONGRANULARITY."

**Comment by davepsilon** [comment]
In the current version of the code, under Windows, the compute method of an SPK object will have an exception - ERROR_MAPPED_ALIGNMENT Windows Error 1132 (0x46C) "The base address or the file offset specified does not have the proper alignment."

**Comment by brandon-rhodes** [comment]
Okay, I will try making the change. Also, I will add this project to my Appveyor account so that I get automated verdicts on whether tests pass instead of having to wait until users run into problems!

**Comment by brandon-rhodes** [comment]
Adding the project to appveyor turns out to have been a bit more work than I wanted to tackle at the moment, so I have made this improvement “blind” without knowing whether it will really help Windows, and have released! The new version is 2.4 and at least the tests pass under Unix, and the new use of ``ALLOCATIONGRANULARITY`` seems to be, as you point out, a better match for the documentation. Let me know if you have any further problems, and thanks so much for the report!
