### ISSUE TITLE
setup.py uses install_requires but no setuptools

### ISSUE THREAD

**Issue by Juanlu001** [brandon-rhodes/python-jplephem#16]
While working on https://github.com/conda-forge/staged-recipes/pull/214#issuecomment-202704047 we discovered that jplephem setup.py is using the option `install_requires`, which exists only in setuptools.

https://docs.python.org/3/search.html?q=install_requires

https://pythonhosted.org/setuptools/setuptools.html#new-and-changed-setup-keywords

I see also that you are mocking the presence of NumPy, perhaps because of this?

Would you consider using `from setuptools import setup` instead of plain distutils? Otherwise the `install_requires` ought to be changed to `requires`.

https://docs.python.org/3/distutils/setupscript.html#relationships-between-distributions-and-packages

**Comment by brandon-rhodes** [comment]
Good guess! But I was faking the presence of NumPy so that, after someone does a `git clone` of the repository, they can successfully run `pip install -e .` to get the project's dependencies installed and ready for development — only after which NumPy will actually be present. :)

I have attempted to fix the `setup.py` problem — can you verify that it looks like I did it correctly before I release a new version for you to use? Thanks!

**Comment by Juanlu001** [comment]
Thanks @brandon-rhodes! The `setup.py` file now looks definitely all right. [`pip install -e .` injects setuptools](https://pip.pypa.io/en/stable/reference/pip/#setuptools-injection), so it is being used anyway. The problem came because it was advised to use `python setup.py install` for conda recipes instead of `pip`.
