### ISSUE TITLE
Velocities units

### ISSUE THREAD

**Issue by voronY** [brandon-rhodes/python-jplephem#19]
Why does `compute_and_differentiate` return velocities as km/day instead of more common km/sec ?

**Comment by brandon-rhodes** [comment]
The result returned by `compute_and_differentiate()` are unitless — the library does not know what physical quantities are represented. An ephemeris accepts an input value `t` and returns values `x` `y` and `z`, none of which have explicitly declared units within the ephemeris file. When you differentiate, you get change-in-`x` (and `y` and `z`) per one unit of change in `t`. But there are no units attached.

Consult the ephemeris you are using to learn what units it uses for its `x` `y` and `z` dimensions, and what units for its `t`. The differential will have as its denominator whichever unit the `t` value has — so if `t` is (as is typical) expressed in days, then the derivative will be per-day, simply by how the math works out. Does that make sense?

**Comment by voronY** [comment]
Yes, it's quit reasonable. But look:  de430.bsp for its `t` uses seconds, but the result is days. And `_load` function explicitly transforms seconds to days: `interval_length = intlen / S_PER_DAY`. Am I right?

**Comment by brandon-rhodes** [comment]
Ah! I see your question now.

The jplephem library was originally for use with special NumPy-reformatted versions of the ASCII formatted JPL ephemerides available here:

ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/ascii_format.txt

As you can see from that file format description, they use JD, which is measured in days, as their inherent time scale. Later, I decided to pivot jplephem towards allowing the user to load and use `.bsp` files formatted for the SPICE library, since those let me skip the step of converting them to binary arrays myself. But there was a wrinkle: the SPICE library uses seconds internally for time, instead of the Julian Days that are the native time format for JPL ephemerides. So, as you have seen, I convert the intervals to days for compatibility with how JPL itself publishes the ephemerides, instead of exposing the fact that the SPICE library thinks of time differently from how the JPL ephemerides themselves originally think of it.

**Comment by brandon-rhodes** [comment]
Oh, and, here it the JPL's overview of the file types it offers:

http://ssd.jpl.nasa.gov/?planet_eph_export

**Comment by voronY** [comment]
Thank you Brandon for the explanation!

**Comment by brandon-rhodes** [comment]
No problem! I hope you find jplephem useful. :)

**Comment by galactics** [comment]
Hi ! Thanks for the question and the explanation !
