### ISSUE TITLE
jplephem on raspberry pi

### ISSUE THREAD

**Issue by oopfan** [brandon-rhodes/python-jplephem#21]
Dear Mr. Rhodes,

I received the following error trying to run "python -m jplephem de430.bsp":

```
...
File "/usr/local/lib/python2.7/dist-packages/jplephem/spk.py", line 38, in __init__
self.segments = [Segment(self.daf, *t) for t in self.daf.summaries()]
AttributeError: 'file' object has no attribute 'summaries'
```

I got the same error on three different bsp files that I downloaded from NAIF and JPL sites:
de430.bsp, de430_1850-2150.bsp, de405.bsp

I installed jplephem on my Raspberry Pi Model 3 using the following:
"sudo pip install jplephem"
It was an error-free installation.

I first suspected that the file format changed, so I looked for SPACIT or BRIEF executable downloads for Windows or Linux but I could find none.

GitHub will not allow me to attach any of the files since they exceed the 10MB limit.
The smallest, de430_1850-2150.bsp, is only 32MB and downloadable here:
ftp://ssd.jpl.nasa.gov/pub/eph/planets/bsp/

Would you do me a huge favor and see if you can open that file with jplephem?  If you can then that tells me that I have a problem on my Pi.

Thank you,
Brian Morgan

**Comment by brandon-rhodes** [comment]
Sorry about that — it was through sheer neglect that I at some point broke the ability of jplephem to be invoked from the command line, and because I had no test of the feature, I had not even noticed that it was not working! I have added a test and released a new version 2.6, which has a fix. Please let me know if you run into any further problems, and thanks VERY much for this bug report!

(I wish I had gotten to it faster, but my schedule has been rather full this year. Once PyCon 2017 is over, hopefully things will return to normal for me!)
