### ISSUE TITLE
Can this read little-endian binary JPL files?

### ISSUE THREAD

**Issue by jamadagni** [brandon-rhodes/python-jplephem#31]
Hello. I already have the little-endian binary JPL files downloaded from ftp://ssd.jpl.nasa.gov/pub/eph/planets/Linux/de431/. But the code/doc seems only to talk about BSP files. 

Does this mean I have to download the files from under ftp://ssd.jpl.nasa.gov/pub/eph/planets/bsp/? 

Since the files aren't small I'm wary of downloading and using up my bandwidth unnecessarily.

Further some of those files have `t` `s` etc appended to the DE version number and I'm not sure what to use…

Please help! Thank you!

**Comment by brandon-rhodes** [comment]
I would suggest starting with a very small pair of files first if bandwidth costs are an issue, and seeing if a small ephemeris is supported before trying a big one. I'm not familiar with the ".431" file extension (I guess it's just the ephemeris number?) so I don't know anything about the format of that particular file. I myself have only used the library with bsp files, since those are the kind currently used by tools like SPICE. My guess is that you'll need a bsp file.

**Comment by brandon-rhodes** [comment]
I'm going to close this for now, but if you have any further questions, please feel free to re-open it and ask them!
