### ISSUE TITLE
Please specify minimal numpy version in setup.py

### ISSUE THREAD

**Issue by SebastianoF** [brandon-rhodes/python-jplephem#35]
Latest version, released 6 hours ago is failing with numpy==1.11.3 due to `cannot import flip`.
... Thanks!

**Comment by brandon-rhodes** [comment]
I would rather continue to support users with old NumPy versions. Let me see about accomplishing the same thing with slicing. Thanks for letting me know about the breakage!

**Comment by brandon-rhodes** [comment]
There. I've released a new version that removes the use of `flip()`, please let me know if it resolves the problem for you!

**Comment by SebastianoF** [comment]
Thanks!!
I'm indeed a user with old numpy version (1.11.3).
The issue was solved on our side pinning to the previous version in our requriements, even if `jplephem` is not directly called in our code. Only not using flip may not be enough for possible future similar breakage. Maybe you can provide an interval of the numpy versions supported (`"package>=0.2,<0.3"`).

**Comment by brandon-rhodes** [comment]
Thanks for the idea, but I would prefer to support as wide a variety of NumPy versions as possible. I do not want to lock down NumPy versions supported and maybe get future users into a bind where they can't make a successful.

> not using flip may not be enough for possible future similar breakage

Good point! I will try adjusting requirements.txt to downgrade to an old NumPy, so that the tests will always run against that NumPy instead of a modern one that might tempt me to use too-modern features.
