### ISSUE TITLE
[Question] Loading part files together?

### ISSUE THREAD

**Issue by TuSKan** [brandon-rhodes/python-jplephem#44]
How to load de441-part1 and de441-part2 together?

**Comment by brandon-rhodes** [comment]
I see only a single file for that ephemeris:

ftp://ssd.jpl.nasa.gov/pub/eph/planets/bsp

Where are you finding the ephemeris split into two parts?

**Comment by TuSKan** [comment]
https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/

**Comment by brandon-rhodes** [comment]
Thank you, I see them now!

The library currently has no support for loading a pair of files like these, unless you manually load both pieces as separate ephemerides and use whichever is appropriate for the date you are interested in.

You will want to use the FTP file for how that keeps the ephemeris in one file rather than two. If an ephemeris is ever distributed only as two pieces, we will have an interested implementation question: should the library become more complicated by loading both files but pretending they are one? Or, should a command be provided that would let users locally combine the two parts into a single ephemeris that their program could then load?

For today, are you able to use the single-file version?

**Comment by TuSKan** [comment]
I didn't know about this ftp address and single file for de441.
I'm fine with that.
I prefer locally combined than make library more complicated.
Thank you very much for answering.
I'm close this question for now

**Comment by brandon-rhodes** [comment]
I am glad you can go ahead and start using the new ephemeris today and won’t have to wait on a new version of jplephem!

I will comment on this issue again in the future if I or another contributor develop code that would support combining a two-part ephemeris into a single file locally. And hopefully anyone else curious about using the new ephemeris with this library will find this issue and download it from the FTP site.
