### ISSUE TITLE
Basic Skyfield on Micropython

### ISSUE THREAD

**Issue by sgbmzm** [brandon-rhodes/python-jplephem#59]
Hello.
Is it possible to run Basic Skyfield on Micropython? I need to calculate sunrise and sunset and also calculate the height of the sun in degrees below the horizon. That's all. The problem is that the resources are very limited in Micropython. There is a total of 2 MB of memory on the ESP-32 device.
Thank you!

**Comment by brandon-rhodes** [comment]
That's an interesting question! I've never tried Micropython out. There would need to be some kind of NumPy equivalent, and the big problem would be loading the big `.bsp` ephemeris files that JPL issues, because Skyfield's underlying `jplephem` library uses `mmap()` to make them available without loading each whole `.bsp` file into memory — but I'm not sure the platforms that Micropython runs on typically have a virtual memory system?

I wonder if SpiceyPy would have a much smaller footprint? I think I ran SPICE briefly once, but I didn't bother to look at its memory footprint. It's written in a low-level language but I don't know if it thereby necessarily puts less stress on a system's resources. (For example, does it try to load whole `.bsp` files into memory or something?)

How accurate do you need to be? I would be tempted to try out the old PyEphem library, and see if its results are close enough to Skyfield's to be useable. A recent build I have sitting here on my machine weighs in at 3.0M — and that includes, internally, tables for where the Sun and Earth are pointed, so I think it runs without additional data files? Don't use it to point an observatory telescope, but it might still predict sunrise within the same minute. Maybe. Try it out 🙂

**Comment by brandon-rhodes** [comment]
(If you need Skyfield precision, another alternative would be to build tables of Sun positions from Skyfield on a normal machine, write them to a file, then write a little script for the Micropython that loaded up those data files and performed the final step or two to turn it into a sunrise prediction?)

**Comment by sgbmzm** [comment]
Regarding ephemeris, i can create a small ephemeris file just of the sun and only of say 5 years and then it will be half a MB. But I'm not sure which bodies must be included: 10, 3, 399
And even after that I don't know how to run Skyfield.
Maybe ulab is a bit similar to NumPy but I don't know if it's enough.
ESP-32 with a small screen is very cheap! (Maybe $5) And I wish I could hang one like that in my house that shows how high the sun is now, and how much time has passed since sunrise.
I also don't know how to run PyEphem on Micropython.
Actually there is
https://github.com/peterhinch/micropython-samples/tree/master/astronomy
which I don't know how accurate but also doesn't include the current sun's height but only sunrise and sunset times.

**Comment by sgbmzm** [comment]
p.s. It seems to me that ESP-32 is 32 bits, and perhaps that is another factor to consider.

**Comment by brandon-rhodes** [comment]
> p.s. It seems to me that ESP-32 is 32 bits, and perhaps that is another factor to consider.

I wonder if it has a 64-bit floating point coprocessor? Or do all the floating point operations need to be performed by dozens of integer operations on its processor core?

Anyway, it looks like the answer is clear: alas, "no, Skyfield does not run on Micropython today, that's too different a platform from mainstream Python for Skyfield and its libraries to operate successfully."

I think I am going to close this issue, as that's not a near-term goal for Skyfield. But please feel free to comment further about any alternative solution you find, as future readers might be interested to learn the direction that your project heads in; but I don't think this belongs on Skyfield's to-do list, as there's plenty of other improvements to stay focused on for Skyfield.

**Comment by sgbmzm** [comment]
Thanks.
I suggest looking here:
https://github.com/peterhinch/micropython-samples/issues/42
I think it's a good place to start.
If you have time to add There some basic methods to the `sun_moon.py` directory I would be very happy.
