### ISSUE TITLE
JPLEphem2.0 with Skyfield

### ISSUE THREAD

**Issue by cnwangfeng** [brandon-rhodes/python-jplephem#8]
How skyfield supports new DE430? Or I have to use DE421?

**Comment by Juanlu001** [comment]
This belongs to python-skyfield instead but you can use the `Kernel` class to load de430 in the same way you would do with python-jplephem.

https://github.com/brandon-rhodes/python-skyfield/blob/master/skyfield/jpllib.py#L15

Other than that, @brandon-rhodes will correct me if I am wrong but I think Skyfield relies on the legacy API.

**Comment by brandon-rhodes** [comment]
I am working on a new Skyfield release, which should emerge by the end of the month, that will encourage the use of SPICE kernels instead of the ad-hoc Python-packaged ephemerides. I am currently, when I have moments to work on the project, working out a few last problems with the new API that SPICE kernels will require.

**Comment by brandon-rhodes** [comment]
The new version Skyfield 0.5 is now out, and supports DE430! You can check out the documentation for ephemerides at:

http://rhodesmill.org/skyfield/planets.html

Enjoy! :)

**Comment by Juanlu001** [comment]
Awesome, thanks! :)
